###
POST {{host}}/api/gpt/recommend
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJJZCI6MjMsIklEWCI6IjM4NTE4NzIzMTQiLCJOQU1FIjoi7J2064-Z7ZuIIiwiZXhwIjoxNzQ2MjIyMjMxfQ.w4YyFemQqNXjmBq7q6_tBW2f-pm67In29MNu7QdDaVy8N1NdTU4KEMl6VAHq2g9joPS-5Cr4VBG07FUcWQkmRg

{
  "age": 7,
  "maxPriceNew": 1000000,
  "maxPriceUsed": 500000,
  "twin": false,
  "type":"CONVERTIBLE",
  "weightType": "NORMAL",
  "carryOn": false,
  "userText": "디자인 이쁘고, 가격도 적당하고, 폴딩이 쉬웠으면 좋겠음"
}
#### 상품상태변경
#POST {{host}}/product/change/status
#Content-Type: application/json; charset=utf-8
#
#{
#"id" : 4,
#"statusType" : "Reserved"
#}