server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: stroller
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379

socket-server:
  port: 8086 # you can change this to a port that is free to use
  host: 127.0.0.1 # change this to your IPv4 address