server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: stroller
    driver-class-name: org.postgresql.Driver
    mongodb:
      uri: mongodb://localhost:27017/chatdb
    #      uri: mongodb://username:password@your-mongo-host:27017/chatdb 원격서버의 경우
  data:
    redis:
      host: localhost
      port: 6379

socket-server:
  port: 8086 # you can change this to a port that is free to use
  host: 127.0.0.1 # change this to your IPv4 address



logging:
  level:
    ROOT: info
    org.springframework.jdbc: debug
    org.springframework.security: debug

file:
  upload-dir: F:\\stroller\\image\\product\\

cookie:
  domain:
    host: localhost

