server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGODB_URI}

logging:
  level:
    ROOT: info

#    sql 작업속도 보려면 주석해재
#    org.hibernate.SQL: info
#    org.hibernate.type.descriptor.sql.BasicBinder: info
#    org.hibernate.stat: off

file:
  upload-dir: /home/stroller/images/product/

cookie:
  domain:
    host: jungmocha.co.kr