server:
  port: 8080

spring:
  datasource:
    #    url: jdbc:h2:mem:testdb
    #    username: sa
    #    password:
    #    driver-class-name: org.h2.Driver
    url: jdbc:postgresql://182.228.21.172:5432/
    username: postgres
    password: stroller3jo
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: info
#    org.hibernate.SQL: info
#    org.hibernate.type.descriptor.sql.BasicBinder: info
#    org.hibernate.stat: off

file:
  upload-dir: /home/stroller/images/product/

cookie:
  domain:
    host: jungmocha.co.kr