server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: stroller
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/chatdb
    #      uri: mongodb://username:password@your-mongo-host:27017/chatdb 원격서버의 경우

logging:
  level:
    ROOT: info
    org.springframework.jdbc: debug
    org.springframework.security: debug

file:
  upload-dir: F:\\stroller\\image\\product\\