### 마이페이지
GET {{host}}/api/user/mypage
Content-Type: application/json; charset=utf-8

### 관심목록
GET {{host}}/api/user/mypage/favorites
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtZW1iZXJJZCI6MjMsIklEWCI6IjM4NTE4NzIzMTQiLCJOQU1FIjoi7J2064-Z7ZuIIiwiZXhwIjoxNzgwOTg0ODYzfQ.lMMJ23YGFh5vRZQoLKiTznVzyBaZhVqVY4ntWo91bGZNxMEBWlK2xL62apcE95VjJ0LHcaS3miJDEp7gAwaApA

### 파는목록
GET {{host}}/api/user/mypage/selling-list
Content-Type: application/json; charset=utf-8